# Generated by Django 5.2.17 on 2026-08-25 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('HATE_SPEECH', 'Hate Speech / Discriminatory Language'), ('UNVERIFIED_DEFAMATION', 'Unverified Personal Defamation against Individual'), ('SPAM', 'Spam / Advertisement / Irrelevant Content'), ('FALSE_LOCATION', 'Fabricated / False GPS Location'), ('PERSONAL_DATA_LEAK', 'Unauthorized Leak of Private Citizen Data / Phone Numbers'), ('OTHER', 'Other Violation of Community Guidelines')], max_length=40)),
                ('explanation', models.TextField()),
                ('anonymous_session_hash', models.CharField(max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='complaints.complaint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModerationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve for Public Feed'), ('REJECT', 'Reject Submission (Spam/Defamation)'), ('FLAG', 'Mark for Strict Verification'), ('REQUEST_REVISION', 'Request Redaction of Named Individual')], max_length=30)),
                ('moderator_name', models.CharField(default='Community Moderator', max_length=100)),
                ('notes', models.TextField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_reviews', to='complaints.complaint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
