# Generated by Django 5.2.17 on 2026-08-25 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_type', models.CharField(choices=[('GRIEVANCE_LETTER', 'Formal Public Grievance Letter (औपचारिक जन शिकायत पत्र)'), ('RTI_APPLICATION', 'Right to Information (RTI / सूचना का अधिकार आवेदन)'), ('PRESS_DOSSIER', 'Media & Press Accountability Dossier')], max_length=40)),
                ('language', models.CharField(choices=[('hi', 'Hindi'), ('en', 'English')], default='hi', max_length=10)),
                ('title_format', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_type', models.CharField(max_length=40)),
                ('language', models.CharField(default='hi', max_length=10)),
                ('addressed_to', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('corroboration_count_at_generation', models.PositiveIntegerField(default=0)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='complaints.complaint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
