# Generated by Django 5.2.17 on 2026-08-25 21:35

import apps.core.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorities', '0001_initial'),
        ('config_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, default=apps.core.utils.generate_public_id, max_length=30, unique=True)),
                ('anonymous_session_hash', models.CharField(db_index=True, max_length=64)),
                ('revealed_identity', models.BooleanField(default=False)),
                ('filer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('filer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue (min 30 chars)')),
                ('people_affected_type', models.CharField(choices=[('ESTIMATE', 'Specific Count'), ('ENTIRE_VILLAGE', 'Entire Village / Gram (संपूर्ण गांव)'), ('ENTIRE_WARD', 'Entire Ward / Mohalla (संपूर्ण वार्ड)'), ('ENTIRE_STREET', 'Entire Street / Gali (पूरी गली)')], default='ESTIMATE', max_length=30)),
                ('people_affected_count', models.PositiveIntegerField(blank=True, null=True)),
                ('prior_attempts_count', models.PositiveIntegerField(default=0)),
                ('prior_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_location', models.CharField(help_text='Village / Hamlet / Ward name / Landmark', max_length=200)),
                ('authority_name_override', models.CharField(blank=True, max_length=150, null=True)),
                ('authority_designation', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('gps_accuracy_meters', models.FloatField(blank=True, null=True)),
                ('manual_address_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('FILED', 'Filed (दर्ज किया गया)'), ('UNDER_REVIEW', 'Under Review (समीक्षा में)'), ('ACKNOWLEDGED', 'Acknowledged (संज्ञान लिया)'), ('IN_PROGRESS', 'In Progress (कार्य प्रगति पर)'), ('RESOLVED', 'Resolved (निस्तारित)'), ('CLOSED_UNRESOLVED', 'Closed Unresolved (अनिस्तारित बंद)')], db_index=True, default='UNDER_REVIEW', max_length=30)),
                ('moderation_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved / Public'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Concern')], db_index=True, default='PENDING', max_length=30)),
                ('is_official_conduct', models.BooleanField(default=False, help_text='Direct complaint on named official conduct')),
                ('co_sign_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('flag_count', models.PositiveIntegerField(default=0)),
                ('administrative_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='authorities.administrativeunit')),
                ('area_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='config_engine.areatype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='config_engine.complaintcategory')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorities.district')),
                ('duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='config_engine.durationoption')),
                ('prior_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_engine.priorchanneloption')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorities.state')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('PHOTO', 'Live Photo Snapshot'), ('VIDEO', 'Live Video Stream (30s)'), ('AUDIO_NOTE', 'Live Audio Voice-Note (60s)')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/')),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('sha256_hash', models.CharField(help_text='Tamper-evident SHA-256 hash of media file', max_length=64)),
                ('capture_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('capture_latitude', models.FloatField(blank=True, null=True)),
                ('capture_longitude', models.FloatField(blank=True, null=True)),
                ('is_live_captured', models.BooleanField(default=True, help_text='Captured via getUserMedia (no gallery picker)')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='complaints.complaint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('actor_type', models.CharField(choices=[('SYSTEM', 'Awaaz System Engine'), ('MODERATOR', 'Public Moderator'), ('AUTHORITY', 'Civic Authority / Official'), ('CITIZEN', 'Citizen Community')], default='SYSTEM', max_length=20)),
                ('actor_label', models.CharField(max_length=150)),
                ('notes', models.TextField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='complaints.complaint')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCoSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anonymous_session_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_signs', to='complaints.complaint')),
            ],
            options={
                'unique_together': {('complaint', 'anonymous_session_hash')},
            },
        ),
    ]
