# Generated by Django 5.2.17 on 2026-08-25 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name_en', models.CharField(max_length=100)),
                ('name_hi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_hi', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_type', models.CharField(choices=[('MUNICIPAL_CORP', 'Municipal Corporation (Nagar Nigam)'), ('ZONE', 'Zone / Division'), ('WARD', 'Ward / Mohalla'), ('NAGAR_PANCHAYAT', 'Nagar Panchayat / Palika Parishad'), ('BLOCK', 'Block / Tehsil / Janpad'), ('GRAM_PANCHAYAT', 'Gram Panchayat'), ('VILLAGE', 'Village / Gaon / Mauza')], max_length=30)),
                ('name_en', models.CharField(max_length=150)),
                ('name_hi', models.CharField(max_length=150)),
                ('ward_number', models.CharField(blank=True, max_length=20, null=True)),
                ('helpline_number', models.CharField(blank=True, max_length=50)),
                ('official_portal_url', models.URLField(blank=True)),
                ('approx_latitude', models.FloatField(blank=True, null=True)),
                ('approx_longitude', models.FloatField(blank=True, null=True)),
                ('area_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_units', to='config_engine.areatype')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='authorities.administrativeunit')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_units', to='authorities.district')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='PublicAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_hi', models.CharField(max_length=150)),
                ('designation_en', models.CharField(max_length=150)),
                ('designation_hi', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('office_address_en', models.TextField(blank=True)),
                ('office_address_hi', models.TextField(blank=True)),
                ('photo_url', models.CharField(blank=True, max_length=255)),
                ('administrative_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorities', to='authorities.administrativeunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='authorities.state'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'code')},
        ),
    ]
